## Tu configuracion original (No la toques)
#spring.datasource.url=jdbc:mysql://localhost:3306/empresa
#spring.datasource.username=root
#spring.datasource.password=root123
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#server.port=8081


# CONFIGURACIoN DE CORREO GMAIL PARA PRODUCCIoN (Puerto Seguro 465)
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=alextbleganes@gmail.com
spring.mail.password=iiqsvxjvwickefps

# Propiedades especificas de encriptacion SSL para saltar el bloqueo de Railway
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.socketFactory.port=465
spring.mail.properties.mail.smtp.socketFactory.class=javax.net.ssl.SSLSocketFactory
spring.mail.properties.mail.smtp.socketFactory.fallback=false


## Configuracion de correo usando tu Gmail personal
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=alextbleganes@gmail.com
#spring.mail.password=iiqsvxjvwickefps
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#
#
# CONFIGURACIoN TRABAJO (H2 en memoria)
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
##
## Esto crea las tablas automaticamente segUn tus clases @Entity
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always
## Para que puedas entrar a ver la base de datos desde el navegador
#spring.h2.console.enabled=true
#
#logging.level.org.springframework.security=DEBUG


#
logging.level.org.springframework.security=DEBUG
# Configuracion de la conexion a Railway
#
spring.datasource.url=jdbc:mysql://root:pKxcMpzeujOWXOmbIwhRALIwRRZIvyhU@yamabiko.proxy.rlwy.net:34634/railway
spring.datasource.username=root
spring.datasource.password=pKxcMpzeujOWXOmbIwhRALIwRRZIvyhU
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# CONFIGURACIoN DE JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect